### ISSUE TITLE
Unknown node properties error not thrown when nodeset is queried without population name

### ISSUE THREAD

**Issue by anilbey** [BlueBrain/snap#193] opened 2023-03-29 10:00 UTC
@KeremKurban noticed the following bug

Here it works fine since "hippocampus_neurons" is selected explicitly.

#### Failure case (with population name)

Raises the error as expected.

```python
(Pdb) self.circuit.nodes["hippocampus_neurons"].ids({"$target": "most_central_10_SP_PC"})
*** bluepysnap.exceptions.BluepySnapError: Unknown node properties: {'$target'}
```

#### Success case (with population name)

Works fine, all is well.

```python
(Pdb) self.circuit.nodes["hippocampus_neurons"].ids({"$node_set": "most_central_10_SP_PC"})
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

Here however (below), upon success it returns the ids but it does not raise the error upon failure.

#### Success case without population name

Works fine, all is well.

```python
(Pdb) self.circuit.nodes.ids({"$node_set": "most_central_10_SP_PC"})
CircuitNodeIds([('hippocampus_neurons', 0),
            ('hippocampus_neurons', 1),
            ('hippocampus_neurons', 2),
            ('hippocampus_neurons', 3),
            ('hippocampus_neurons', 4),
            ('hippocampus_neurons', 5),
            ('hippocampus_neurons', 6),
            ('hippocampus_neurons', 7),
            ('hippocampus_neurons', 8),
            ('hippocampus_neurons', 9)],
           names=['population', 'node_ids'])
```

#### Failure case without population name

Does **not raise** the error.

```python
(Pdb) self.circuit.nodes.ids({"$target": "most_central_10_SP_PC"})
CircuitNodeIds([], names=['population', 'node_ids'])

```

**Comment by joni-herttuainen** [comment] 2023-04-03 06:48
I'll go with the classic explanation: It's not a bug, it's a feature.

Further explanation:
The function `circuit.nodes.ids` uses `circuit.nodes['node_population'].ids` when it is gathering the `CircuitNodeId`s. However, we can not be as strict when raising errors for missing properties since we would end up in a situation in which 
```python
circuit.nodes.ids({'mtype': 'VPL_TC'})
```
would raise an error with a circuit config, in which there are projections (i.e., virtual node populations) present and would render the function next to useless.

**Comment by joni-herttuainen** [comment] 2023-05-15 12:41
As this is not a bug, I will close the issue. If you want uniformity between the two, I suggest using the `raise_missing_property` flag when calling `nodes['population'].ids`:
```python
self.circuit.nodes["hippocampus_neurons"].ids(
    {"$target": "most_central_10_SP_PC"}, raise_missing_property=False
)
```

Whether raising should be a default option or not with the `population.ids(...)` is debatable.

**Closed as completed by joni-herttuainen** 2023-05-15 12:41 UTC
