### ISSUE TITLE
Simulation: retrieve connection_overrides in the order they are read from the file.

### ISSUE THREAD

**Issue by anilbey** [BlueBrain/snap#181] opened 2023-02-06 17:48 UTC
The order of `connection_overrides` affects the simulation results. We need a way of retrieving the `connection_overrides` in the order they are written to the simulation_config file.

https://sonata-extension.readthedocs.io/en/latest/sonata_simulation.html#connection-overrides

**Comment by anilbey** [comment] 2023-04-03 10:44
I didn't know in python3.7+ dict was guaranteed to preserve the insertion order. All is well, then. This is no longer an issue.
https://docs.python.org/3/whatsnew/3.7.html

> Python data model improvements:
> 
>     [PEP 562](https://docs.python.org/3/whatsnew/3.7.html#whatsnew37-pep562), customization of access to module attributes.
> 
>     [PEP 560](https://docs.python.org/3/whatsnew/3.7.html#whatsnew37-pep560), core support for typing module and generic types.
> 
>     the insertion-order preservation nature of [dict](https://docs.python.org/3/library/stdtypes.html#typesmapping) objects [has been declared](https://mail.python.org/pipermail/python-dev/2017-December/151283.html) to be an official part of the Python language spec.

**Comment by mgeplf** [comment] 2023-04-03 12:03
The problem is that we don't have any guarantees about the underlying json reader:  the json spec says that objects are unordered: https://json.nlohmann.me/features/object_order/

It seems that we'll need to change the SONATA spec so that we use a list instead, if order matters.

**Comment by mgeplf** [comment] 2023-04-03 12:36
Can you open a ticket in https://github.com/BlueBrain/sonata-extension/?

**Comment by mgeplf** [comment] 2023-04-05 09:15
I'm going to close this; and once the spec is changed, we'll support whatever the decision is.  Thanks.

**Closed by mgeplf** 2023-04-05 09:15 UTC
